# Config file for automatic testing at travis-ci.org

dist: xenial
language: python
services:
  - postgresql
  - redis-server
matrix:
    include:
      - python: 3.7
        env: TOXENV=py37

install:
  - pip install -U tox-travis coveralls
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt

before_script:
  - psql -c 'create database defaultdb;' -U postgres
  - hug -f service.py &
  - sleep 2

script: tox

after_success:
  - coveralls
